image: python:3.9

tasks:
  # Since Gitpod doesn't support caching custom Dockerfiles yet, this is the best we can do for now to
  # install all dependencies as well as the Vale linter.
  - before: |
      pip install -r docs/requirements.txt
      mkdir -p /vale
      pushd /vale
      VALE_VERSION=2.15.1
      wget https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz
      tar -xf 'vale_${VALE_VERSION}_Linux_64-bit.tar.gz'
      export PATH="/vale:${PATH}"
      popd
      vale --version
    command: gp open .vscode/welcome.md

vscode:
  extensions:
    - lextudio.restructuredtext
    - trond-snekvik.simple-rst
    - errata-ai.vale-server
    - ms-python.python
    - eamodio.gitlens

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
